### YamlMime:Lifecycle
metadata:
  title: Upravljač konfiguracije sistema Microsoft System Center 2012
  description: Upravljač konfiguracije sistema Microsoft System Center 2012 sledi smernice za životni ciklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: dce8796f280b29e070bbf1d5bab55452f6e706e7
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862027"
name: Upravljač konfiguracije sistema Microsoft System Center 2012
summary: >+
  Upravljač konfiguracije sistema Microsoft System Center 2012 sledi smernice [za životni ciklus](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 2
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Service Pack 1
  startDate: 12/15/2012
  endDate: 07/12/2016
- version: Original Release
  startDate: 05/30/2012
  endDate: 01/14/2014
content: "\n## <a name=\"links\"></a>Veze \n* [Smernica servisnog paketa](/lifecycle/policies/fixed#service-packs)\n* [Dokumentacija sistemskog centra](/system-center/#pivot=components&panel=components-all)\n* [Resursi sistemskog centra](https://www.microsoft.com/system-center/resources)"
