### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 za radne površine operativnog sistema Windows
  description: Microsoft Application Virtualization Hosting 5.1 za Windows računare sledi fiksne smernice za životni ciklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862140"
name: Microsoft Application Virtualization Hosting 5.1 za radne površine operativnog sistema Windows
summary: >+
  Microsoft Application Virtualization Hosting 5.1 za Windows računare sledi [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


  Ovo se odnosi na sledeća izdanja: za Windows računare

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Izdanja \n* Za Windows računare"
