### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security prati fiksne smernice za životni ciklus.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security prati [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Veze 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security je obustavljen od 14. jula 2015. Ispravke definicija antimalvera i antispajvera više neće biti dostupne od završetka podrške za verziju proizvoda. Molimo vas, ocenite System Center Endpoint Protection kao zamenu.