### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 prati fiksne smernice za životni ciklus.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 prati [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


  > [!IMPORTANT]
  > Podrška za ovaj proizvod je završena. Pogledajte dolenavedena uputstva za migraciju.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Veze 
  * [Smernice za migracije](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Dodatni vodič za migraciju](/mem/configmgr/core/migration/planning-for-migration)