### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 za radne površine operativnog sistema Windows
  description: Microsoft Application Virtualization Hosting 4.6 za Windows računare prati fiksne smernice za životni ciklus.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153938"
name: Microsoft Application Virtualization Hosting 4.6 za radne površine operativnog sistema Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 za Windows računare prati [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


  Ovo se odnosi na sledeća izdanja: za Windows računare

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu i migraciji](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Smernice za servisne pakete](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Pošto klijent App-V 4.6 koristi App-V 4.5 Server, App-V 4.5 Server će i dalje biti podržan u skladu sa datumima životnog ciklusa za App-V 4.6 kada se koristi sa podržanim klijentom App-V 4.6.\n\n## <a name=\"editions\"></a>Izdanja \n* Za Windows računare"
