### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 za Windows radne površine
  description: Microsoft Application Virtualization Hosting 5.1 za Windows radne površine sledi fiksne smernice za životni ciklus.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 9296a136a0bc0da5a6d6b6b8b49d012170158da0
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1000590"
name: Microsoft Application Virtualization Hosting 5.1 za Windows radne površine
summary: >+
  Microsoft Application Virtualization Hosting 5.1 za Windows radne površine sledi [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


  Ovo se odnosi na sledeća izdanja: za Windows radne površine

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Izdanja \n* Za Windows radne površine"
