### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 za radne površine operativnog sistema Windows
  description: Microsoft Application Virtualization Hosting 5.1 za Windows računare sledi fiksne smernice za životni ciklus.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 za radne površine operativnog sistema Windows
summary: |+
  Microsoft Application Virtualization Hosting 5.1 za Windows računare sledi [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.

  Ovo se odnosi na sledeća izdanja: za Windows računare

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Veze 
  * [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Izdanja 
  * Za Windows računare