### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 za radne površine operativnog sistema Windows
  description: Microsoft Application Virtualization Hosting 4.6 za Windows računare prati fiksne smernice za životni ciklus.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.6 za radne površine operativnog sistema Windows
summary: |+
  Microsoft Application Virtualization Hosting 4.6 za Windows računare prati [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.

  Ovo se odnosi na sledeća izdanja: za Windows računare

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Veze 
  * [Informacije o proizvodu i migraciji](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Smernice za servisne pakete](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Pošto klijent App-V 4.6 koristi App-V 4.5 Server, App-V 4.5 Server će i dalje biti podržan u skladu sa datumima životnog ciklusa za App-V 4.6 kada se koristi sa podržanim klijentom App-V 4.6.

  ## <a name="editions"></a>Izdanja 
  * Za Windows računare