### YamlMime:Lifecycle
metadata:
  title: Microsoft Desktop virtuelizacija aplikacija hosting 5,1 za Windows Desktop računare
  description: Microsoft Application virtuelizacija aplikacija 5,1 za Windows Desktop računare sledi smernice za fiksno životni ciklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "862140"
name: Microsoft Desktop virtuelizacija aplikacija hosting 5,1 za Windows Desktop računare
summary: >+
  Microsoft Application virtuelizacija aplikacija 5,1 za Windows Desktop računare sledi smernice za [Fiksno](/lifecycle/policies/fixed) životni ciklus.


  Ovo se primenjuje na sledeće izdanja: za Windows Desktop računare

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Izdanja \n* za Windows Desktop računare"
