### YamlMime:Lifecycle
metadata:
  title: Virtuelizacija aplikacije SoftGrid
  description: Virtuelizacija aplikacije SoftGrid dolazi nakon osnovnih smernica za životni ciklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "836482"
name: Virtuelizacija aplikacije SoftGrid
summary: >
  Virtuelizacija aplikacije SoftGrid dolazi nakon [osnovnih](/lifecycle/policies/fixed) smernica za životni ciklus.


  Ovo se primenjuje na sledeće izdanja: 4,1 za stoni, 4,2 za stoni, za usluge terminala 4,1


  > [!IMPORTANT]

  > Podrška je prekinuta. Pogledajte dolenavedena uputstva za migraciju.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Veze \n* [Vodič za migraciju](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Izdanja \n* 4,1 za stoni\n* 4,2 za stoni\n* za usluge terminala 4,1"
