### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization prati fiksne smernice za životni ciklus.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 5009a44f0d0ab2b180f62474de8f4d4bb01e3e62
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: sr-Latn-RS
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001034"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization prati [fiksne](/lifecycle/policies/fixed) smernice za životni ciklus.


  Ovo se odnosi na sledeća izdanja: 4.1 za radne površine, 4.2 za radne površine, za usluge terminala 4.1


  > [!IMPORTANT]

  > Podrška se završila. Pogledajte dolenavedena uputstva za migraciju.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Veze \n* [Smernice za migracije](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Izdanja \n* 4.1 za radne površine\n* 4.2 za radne površine\n* za usluge terminala 4.1"
